info:
  contact: {}
  description: Go 语言编程
  termsOfService: https://github.com/
  title: HIVE
  version: "1.0"
paths:
  /auth/captcha:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 获取验证码API
      tags:
      - CaptchaResult
swagger: "2.0"
